image:
  pullPolicy: IfNotPresent
  repository: "renovate/renovate"
  tag: 39.238.1

initContainer:
  name: "renovate-init-container"
  image: "renovate-init-container:1.0.8"
  command: 'cp /configmap/generate-token.sh /tmp/generate-token.sh && chmod +x /tmp/generate-token.sh && sh /tmp/generate-token.sh'
  envFromSecret: renovate

suspend: true

env:
  - name: LOG_LEVEL
    value: DEBUG
  - name: RENOVATE_CONFIG_FILE
    value: '/configmap/config.json'

command: '. /tmp/secret.env && renovate'

volumes:
  config:
    configmap:
      name: tmp-volume

extraVolumes:
  - name: my-extra-volume
    configMap:
      name: renovate-configmap

extraVolumeMounts:
  - name: my-extra-volume
    mountPath: /configmap
