---
apiVersion: v1
kind: ConfigMap
metadata:
  name: renovate-configmap
data:
  config.json: |-
    {
      "platform": "github",
      "onboarding": false,
      "detectHostRulesFromEnv": true,
      "autodiscover": true,
      "autodiscoverFilter": [
        "my-lit-organization/my-second-deploy"
      ]
    }
  generate-token.sh: |-
{{ .Files.Get "scripts/generate-token.sh" | indent 4}}
